### ISSUE TITLE
Aktivitätsdiagramm u12 und u13

### ISSUE THREAD

**Issue by WolframSRC** [thomasgor/swe#14]
"In Raum eingeloggen", Formulierungen erste Bubble überarbeiten

**Comment by Floix1991** [comment]
Umformulierungen und im Lastenheft aktualisiert:
Homescreen (aktive Sitzung) = Klickt auf "Home", hat sich eingeloggt oder QR-Code nicht erfolgreich eingescannt
Homescreen (aktive Sitzung)= Klickt auf "Home", hat sich eingeloggt oder hat sich im Raum eingecheckt
