### ISSUE TITLE
Namen der App

### ISSUE THREAD

**Issue by thomasgor** [thomasgor/swe#2]
Der kunde will gerne 3 verschiedene Namen, damit er sich später entscheiden kann

**Comment by MatthiasSWE** [comment]
FreeSpace, FindAPlace2be, Raumzeit

**Comment by Milkybrown** [comment]
Also zu FreeSpace und FindAPlace2Be hatten die Kunden noch garnichts gesagt, etwas trockenes wie Campus Raumfinder oder so fanden die nicht gut. Vielleicht noch ein zwei Vorschläge ausdenken und dann frage ich nochmal per Mail nach?

**Comment by thomasgor** [comment]
Damit wir nciht alle Dialoge immer neu machen müssen, haben wir einfach APPNAME reingeschrieben.
Am Anfang des Heftes kann man das definieren

**Comment by doktormerlin** [comment]
Wenn die Kunden etwas zu FreeSpace sagen, ist den Vertriebmanagern ja auch erlaubt zu erwähnen, dass das nur unser interner Projektname ist ;)

**Comment by Milkybrown** [comment]
Jaja klar, haben wir gesagt und dannach die Vorschläge geäussert, wobei die dazu noch nichts gesagt haben.
