### ISSUE TITLE
Inhaltsverzeichnis

### ISSUE THREAD

**Issue by Milkybrown** [thomasgor/swe#27]
Dialoge ist im Text als Überschrift 2 markiert, im Inhaltsverzeichnis jedoch als eigenes Kapitel ohne Zahl angezeigt.  Muss Punkt 5.3 sein (ist so im Beispiellastenheft). Dann sähe es aber im Verzeichnis gleich aus, wie die einzelnen Dialoge, also muss eins von beiden von der Schriftart angepasst werden. Außerdem fehlen im Inhaltsverzeichnis alle Aktivitäten.

**Comment by doktormerlin** [comment]
Überschriften der Dialoge und Aktivitäten ist jetzt Überschrift 2, Inhaltsverzeichnis ist jetzt korrekt
