### ISSUE TITLE
"Masterpasswort setzen" ist "Masterpasswort eingeben"

### ISSUE THREAD

**Issue by doktormerlin** [thomasgor/swe#29]
Masterpasswort **setzen** klingt so als ob es geändert wird (was ja im Admininterface passiert), nicht so als ob es eingegeben wird um Professor zu werden

**Comment by IrvineML** [comment]
Aktivität u61

**Comment by doktormerlin** [comment]
Im Aktivitätsdiagramm ist es noch falsch
