### ISSUE TITLE
Lastenheft Texte komplett überarbeiten

### ISSUE THREAD

**Issue by doktormerlin** [thomasgor/swe#30]
Die Texte im Lastenheft sind überhaupt nicht auf das MUSS-SOLLTE-WIRD Prinzip angepasst!

**Comment by IrvineML** [comment]
Das stimmt nicht. Die Texte der Aktivitätsdiagramme wurden angepasst

**Comment by doktormerlin** [comment]
Mal ein Beispiel:
u00:

> Klickt der Benutzer nun auf Login, wird auf lokal hinterlegte Google-Konten geprüft
> Bei Auswahl eines Google-Kontos wird der Benutzer einmalig um Zustimmung der Zugriffsrechte auf die Daten des Google-Kontos gebeten.
> Sowohl bei Verweigerung der Zugriffsrechte, als auch bei negativer Prüfung des Kontos wird auf den Login-Bildschirm zurückgeleitet.
> Sollte der Benutzer kein Google-Konto hinterlegt haben, wird er zu einer Google Registrierung weitergeleitet und muss bei erfolgreicher Registrierung auf den Home-Bildschirm geleitet werden.

(WIRD ist eine zukünftige Entwicklung, falsches Wort)

**Comment by IrvineML** [comment]
Es gibt noch Verbesserungspotential

**Comment by IrvineML** [comment]
Allerdings ist das im Musterlastenheft auch nicht konsequent so durchgezogen.

**Comment by Floix1991** [comment]
Hmm, so falsch finde ich das hier gar nicht. Im Kontext bedeutet das "wird" dort, dass nach dem Vorgang von z.B. nach dem "Login"-Klicken etwas passiert (das ist klar Futur und stimmt so). Bei dem MUSS-SOLL-WIRD Prinzip würde man das - nach meinem Verständnis- viel klarer formulieren -> Der Anwender wird in der Lage sein zukünftig etwas zu tun (Der Fokus liegt dann darauf, dass der Anwender eine Möglichkeit bekommen wird, nicht dass eine Aktion auf eine andere Aktion folgt -> meiner Meinung nach ist das ein Unterschied aber ich lasse mich gerne eines besseren belehren :-) )
