### ISSUE TITLE
Anmerkungen: Grundsätzliches

### ISSUE THREAD

**Issue by pdoldotdev** [thomasgor/swe#32]
Grundsätzliches: Name fehlt
Inhaltsverzeichnis: 
- Bezeichnung “Inhaltsverzeichnis” fehlt.
- Unübersichtlich - “Punkte fehlen”

1. Es ist nicht beschrieben was der Begriff "App" bedeutet.

**Comment by pdoldotdev** [comment]
- App Beschreibung in Glossar eingefügt
- Bezeichnung Inhaltsverzeichnis hinzugefügt als Titel 
- Wie kann man das Inhaltsverzeichnis übersichtlicher gestalten?? außerdem habe ich keine Punkte gefunden die fehlen

**Comment by phildol** [comment]
Bezeichnung Inhaltsverzeichnis hinzugefügt als Überschrift 1 wie auch die Kaptiel Überschriften
weiß nicht ob man das so lassen sollte
