### ISSUE TITLE
Anglizismen und IT-Begriffe

### ISSUE THREAD

**Issue by WolframSRC** [thomasgor/swe#7]
Begriffe wie "Tag" sollen klar definiert sein. Der Kunde schlug eine Definition im Glossar vor. Dort sollen auch andere IT-spezifische Begriffe definiert werden, die dem "Otto Normalverbraucher" nicht bekannt sind

**Comment by Milkybrown** [comment]
In den Aktivitätsdiagrammen Screen durch Bildschirm und Button durch Knopf ersetzen.
